name: Docker build

on:
  push:
    branches:
      - main
    # This workflow takes a while, let's only run it when we touch relevant files
    paths:
      - pytorch.yml
      - .github/workflows/docker.yml
      - Dockerfile
  pull_request:
    # This workflow takes a while, let's only run it when we touch relevant files
    paths:
      - pytorch.yml
      - .github/workflows/docker.yml
      - Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.repository == 'coiled/examples' && github.event_name == 'push'  && github.ref == 'refs/heads/main'}}
          platforms: linux/amd64
          tags: coiled/gpu:latest,coiled/gpu:${{ github.sha }}
