name: Docker build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: "coiled/gpu"
            target: "base"
          - repo: "coiled/gpu-examples"
            target: "examples"
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build ${{ matrix.repo }} image and push
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.repository == 'coiled/examples' && github.event_name == 'push'  && github.ref == 'refs/heads/main'}}
          platforms: linux/amd64
          target: ${{ matrix.target }}
          tags: ${{ matrix.repo }}:latest,${{ matrix.repo }}:${{ github.sha }}