name: Docker build

on:
  push:
    branches:
      - main
      # FIXME: Remove this branch before merging
      - gpu-docker
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          # push: ${{ github.repository == 'coiled/examples' && github.event_name == 'push'  && github.ref == 'refs/heads/main'}}
          # FIXME: Only push to dockerhub on pushes to `main`
          push: ${{ github.repository == 'coiled/examples' && github.event_name == 'push' }}
          platforms: linux/amd64
          tags: coiled/gpu:latest
